set-option -g mouse on
set -g history-limit 32768
set -g default-shell /opt/homebrew/bin/fish
set -g default-command /opt/homebrew/bin/fish
set -g focus-events on

bind '%' split-window -h -c '#{pane_current_path}'  # Split panes horizontal
bind '"' split-window -v -c '#{pane_current_path}'  # Split panes vertically
bind c new-window -c '#{pane_current_path}' # Create new window
