#!/bin/bash

# Curl is needed for installation
sudo apt-get install -y curl

# Install latest stable version
wget --continue https://static.rust-lang.org/rustup.sh
sh ./rustup.sh --disable-sudo --prefix=$LOCAL_PREFIX --yes

# Get latest sources

mkdir -p $LOCAL_PREFIX/src/rust
git clone --depth=1 https://github.com/rust-lang/rust $LOCAL_PREFIX/src/rust
